DROP TABLE IF EXISTS `article_bodies`;
DROP TABLE IF EXISTS `articles`;

CREATE TABLE `articles`(
  `id` INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
  `title` VARCHAR(255) NOT NULL,
  `abstruct` VARCHAR(50) NOT NULL,
  `posting_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `article_bodies`(
  `id` INT UNSIGNED NOT NULL PRIMARY KEY,
  `body` VARCHAR(2000) NOT NULL,
  FOREIGN KEY(`id`) REFERENCES `articles`(`id`) ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
